name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  backend:
    name: Backend Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
          check-latest: true
          cache: false

      - name: Install dependencies
        run: |
          go version
          go env
          go mod tidy
        working-directory: backend

      - name: Run tests
        run: go test ./...
        working-directory: backend

  frontend:
    name: Frontend Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - name: Run tests
        run: npm run test
        working-directory: frontend

  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    needs: [backend, frontend]
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20
          check-latest: true
          cache: false

      - name: Verify Go version
        run: go version
        working-directory: backend

      - name: Install dependencies
        run: |
          go version
          go env
          go mod tidy 
        working-directory: backend

      - name: Build Go binary
        run: |
          ls -la
          if [ ! -d "backend" ]; then echo "Error: backend directory not found"; exit 1; fi
          cd backend
          go mod tidy
          GOOS=linux GOARCH=amd64 go build -o bootstrap main.go
          zip function.zip bootstrap

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Deploy Backend to AWS Lambda
        run: |
          aws lambda update-function-code --function-name RendallaBackend --zip-file fileb://backend/function.zip
      
      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build
      
      - name: Deploy Frontend to AWS S3
        run: |
          if [ ! -d "frontend/dist" ]; then echo "Error: frontend/dist directory not found"; exit 1; fi
          aws s3 sync frontend/dist s3://rendalla-bucket --delete
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
      